version: 2

models:
  - name: std_customers_info_ss
    description: '{{ doc("std_customers_info_ss") }}'
    columns:
      - name: customer_id
        description: Unique identifier for each customer.
        data_type: integer
        tests:
          - not_null
          - unique
      - name: customer_name_hashed
        description: Hashed name of the customer.
        data_type: string
      - name: customer_group_id
        description: Group ID for which customer belong.
        data_type: integer
      - name: customer_email_hashed
        description: Hashed email of the customer.
        data_type: string
      - name: customer_phone_number_hashed
        description: Hashed phone number of the customer.
        data_type: string
  - name: std_customer_groups_info_ss
    description: '{{ doc("std_customer_groups_info_ss") }}'
    columns:
      - name: customer_group_id
        description: Group for which customer belong.
        data_type: integer
        tests:
          - not_null
          - unique
      - name: customer_group_type
        description: Type of the group.
        data_type: string
      - name: customer_group_name
        description: Name of the group.
        data_type: string
      - name: customer_group_register_number
        description: Register number of the group.
        data_type: string