version: 2

models:
  - name: airplane_metrics_ss
    description: '{{ doc("airplane_metrics_ss") }}'
    columns:
      - name: airplane_id
        description: Unique identifier for each airplane.
        data_type: string
        tests:
          - not_null
      - name: manufacturer
        description: Manufacturer of the airplane.
        data_type: string
      - name: model
        description: Model of the airplane.
        data_type: string
      - name: max_seats
        description: Maximum seating capacity of the airplane.
        data_type: integer
      - name: max_weight
        description: Maximum weight capacity of the airplane in kilograms.
        data_type: float
      - name: max_distance
        description: Maximum distance the airplane can travel in kilometers.
        data_type: float
      - name: engine_type
        description: Type of engine used in the airplane.
        data_type: string
      - name: trip_end_date
        description: End date of the trip, used for grouping and incremental logic.
        data_type: date
      - name: total_trips
        description: Total number of trips completed by the airplane.
        data_type: integer
      - name: total_customers
        description: Total number of distinct customers served by the airplane.
        data_type: integer
      - name: total_revenue
        description: Total revenue generated by the airplane's trips.
        data_type: float
      - name: total_flight_time_minutes
        description: Total flight time for all trips in minutes.
        data_type: integer
