version: 2

models:
  - name: customer_group_metrics_ss
    description: '{{ doc("customer_group_metrics_ss") }}'
    columns:
      - name: customer_group_id
        description: >
          Unique identifier for the customer group. Defaulted to 'No Groups ID' if not available.
        data_type: string
      - name: customer_group_type
        description: The type of the customer group (e.g., corporate, individual).
        data_type: string
      - name: customer_group_name
        description: The name of the customer group.
        data_type: string
      - name: customer_group_register_number
        description: The registration number associated with the customer group.
        data_type: string
      - name: status
        description: The status of the trips (e.g., completed, pending).
        data_type: string
      - name: number_of_trips
        description: Total number of trips associated with the customer group.
        data_type: int
      - name: total_price
        description: Total revenue generated by trips associated with the customer group.
        data_type: float
      - name: trip_end_date
        description: The date when the trips ended, used as part of the unique key for incremental processing.
        data_type: int
